### ISSUE TITLE
Update Docs Getting Started to use OOD

### ISSUE THREAD

**Issue by mirestrepo** [brown-bnc/bnc-user-manual#2]

**Comment by mirestrepo** [comment]
@elizabethlorenc Did you finish this one, or was it still in progress? Feel free to update status! And thanks for taking on this!

**Comment by elizabethlorenc** [comment]
@mirestrepo I think we can close the issue for now, and add additional OOD tips and tricks in the future as we discover them!

**Comment by mirestrepo** [comment]
Sounds great! Thank you!
